version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.09-node
    working_directory: ~/repo
    environment:
      LANG: en_US.UTF-8
      NODE_ENV: development
      JAVA_OPTS: "-Xms512m -Xmx4g"
      GRADLE_OPTS: '-Xmx4g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError"'

  rn-executor:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo
    environment:
      LANG: en_US.UTF-8
      NODE_ENV: development

jobs:
  install_dependencies:
    executor: rn-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ arch }}-{{ .Branch }}
            - v1-npm-
      - run:
          name: Install Node.js dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - package-lock.json

  build_android:
    executor: android-executor
    resource_class: xlarge
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Ruby dependencies
          command: |
            cd android
            bundle install
            bundle update fastlane
      - run:
          name: Accept Android SDK licenses
          command: yes | sdkmanager --licenses || true
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
            - v1-gradle-
      - run:
          name: Build Android APK (release)
          command: |
            cd android
            ./gradlew assembleRelease --no-daemon --stacktrace
      - save_cache:
          key: v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
          paths:
            - ~/.gradle
            - android/.gradle
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: android_apk

  build_ios:
    macos:
      xcode: "16.1.0"
    resource_class: macos.m1.medium.gen1
    working_directory: ~/repo
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Ruby dependencies
          command: |
            cd ios
            bundle update
            bundle install
      - restore_cache:
          keys:
            - v1-pods-{{ checksum "ios/Podfile.lock" }}
            - v1-pods-
      - run:
          name: Install CocoaPods
          command: |
            cd ios
            bundle exec pod install
      - save_cache:
          key: v1-pods-{{ checksum "ios/Podfile.lock" }}
          paths:
            - ios/Pods
            - ~/.cocoapods
      - run:
          name: Setup SSH for Match
          command: |
            mkdir -p ~/.ssh
            echo "$MATCH_GIT_SSH_KEY" | base64 --decode > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
            cat >> ~/.ssh/config \<< 'EOF'
            Host github.com-fastlane-match
              HostName github.com
              User git
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
            EOF
      - run:
          name: Build and upload to TestFlight
          command: |
            cd ios
            bundle exec fastlane beta
      - run:
          name: Display App Version and Build Number
          command: |
            APP_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" ios/nolimitseradeals/Info.plist)
            BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" ios/nolimitseradeals/Info.plist)
            echo "App Version: $APP_VERSION"
            echo "Build Number: $BUILD_NUMBER"
      - store_artifacts:
          path: ios/output
          destination: ios_build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies:
          context:
            - nolimitsera-context
      - build_android:
          context:
            - nolimitsera-context
          requires:
            - install_dependencies
      - build_ios:
          context:
            - nolimitsera-context
          requires:
            - install_dependencies