def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# Configure react-native-permissions
setup_permissions([
  'Contacts',
  'LocationWhenInUse'
])

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Set environment variable for react-native-maps to use Google Maps
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def shared_pods
  config = use_native_modules!
  
  # react-native-permissions v5.x uses auto-linking
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  return config
end

target 'nolimitseradeals-staging' do
  config = shared_pods
end

target 'nolimitseradeals-prod' do
  config = shared_pods
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    "../node_modules/react-native",
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
  
  # Fix Xcode 16 duplicate output files for React-Core privacy bundle
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'React-Core.common-React-Core_privacy'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
  
  # Deduplicate resource bundles
  installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end